version: '3.8'

services:
  spotify-slsk:
    build: .
    #image: ghcr.io/guilhermewolf/spotify-slsk/spotify-slsk:latest
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./downloads:/downloads
      - ./playlists:/playlists
    depends_on:
      - slskd
    #restart: unless-stopped

  slskd:
    image: slskd/slskd:latest
    env_file:
      - .env
    volumes:
      - ./downloads:/downloads
      - ./downloads/incomplete:/downloads/incomplete
      - ./slsk_app:/app
    ports:
      - "5030:5030"
  #   # restart: unless-stopped

