version: '3.8'

services:
  spotify-slsk:
    build: .
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - ./data:/app/data
    ports:
      - "5110:5110"
    #restart: unless-stopped
